version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dashvalidator-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dashvalidator
      POSTGRES_USER: dashvalidator_user
      POSTGRES_PASSWORD: DashValidator2024
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashvalidator_user -d dashvalidator"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dashvalidator-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
