name: Deploy FacNet Validator
# Manual deployment trigger to restart PM2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ubuntu
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Navigate to application directory
          sudo -u facnet -i bash << 'EOF'
          cd /var/www/facnet/app

          # Delete any existing PM2 processes (clean slate)
          pm2 delete facnet-validator 2>/dev/null || echo "No existing processes to delete"

          # Initialize git repository if it doesn't exist
          if [ ! -d ".git" ]; then
            echo "Initializing git repository..."
            git init
            git remote add origin https://github.com/montignypatrik/facnet-validator.git
            git fetch origin
            git checkout -b main origin/main
          else
            # Pull latest changes
            git fetch origin
            git reset --hard origin/main
          fi

          # Install ALL dependencies (including devDependencies for building)
          npm ci

          # Build application
          npm run build

          # Remove devDependencies to save space (optional)
          npm prune --production

          # Run database migrations
          npm run db:push

          # Start application with PM2 using config file
          pm2 start ecosystem.config.cjs

          # Save PM2 configuration
          pm2 save

          # Check application status
          sleep 5
          pm2 status facnet-validator

          echo "Deployment completed successfully!"
          EOF

    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ubuntu
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Check if application is responding
          sleep 10
          curl -f -k https://148.113.196.245 > /dev/null && echo "✅ Application is responding" || echo "❌ Application is not responding"

          # Check PM2 status as facnet user
          sudo -u facnet pm2 status facnet-validator