name: Deploy FacNet Validator
# Manual deployment trigger to restart PM2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Create deployment archive
      run: |
        tar -czf deployment.tar.gz \
          dist/ \
          server/ \
          shared/ \
          drizzle/ \
          package.json \
          package-lock.json \
          ecosystem.config.cjs \
          drizzle.config.ts \
          tsconfig.json

    - name: Upload build artifacts to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ubuntu
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "deployment.tar.gz"
        target: "/tmp/"

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ubuntu
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Navigate to application directory
          sudo -u facnet -i bash << 'EOF'
          cd /var/www/facnet/app

          # Delete any existing PM2 processes (clean slate)
          pm2 delete facnet-validator 2>/dev/null || echo "No existing processes to delete"

          # Extract deployment archive
          tar -xzf /tmp/deployment.tar.gz -C /var/www/facnet/app/
          rm /tmp/deployment.tar.gz

          # Install production dependencies only
          npm ci --only=production

          # Run database migrations
          npm run db:push

          # Start application with PM2 using config file
          pm2 start ecosystem.config.cjs

          # Save PM2 configuration
          pm2 save

          # Check application status
          sleep 5
          pm2 status facnet-validator

          echo "Deployment completed successfully!"
          EOF

    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ubuntu
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Check if application is responding
          sleep 10
          curl -f -k https://148.113.196.245 > /dev/null && echo "✅ Application is responding" || echo "❌ Application is not responding"

          # Check PM2 status as facnet user
          sudo -u facnet pm2 status facnet-validator