name: Deploy FacNet Validator
# Manual deployment trigger to restart PM2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ubuntu
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Execute deployment as facnet user with explicit error handling
          sudo -u facnet bash -c '
          set -e  # Exit on any error
          cd /var/www/facnet/app

          echo "=== Starting Deployment ==="
          echo "Current directory: $(pwd)"

          # Initialize git repository if it doesn'"'"'t exist
          if [ ! -d ".git" ]; then
            echo "Initializing git repository..."
            git init
            git remote add origin https://github.com/montignypatrik/facnet-validator.git
            git fetch origin
            git checkout -b main origin/main
          else
            echo "Pulling latest changes..."
            git fetch origin
            git reset --hard origin/main
            echo "Latest commit: $(git log -1 --oneline)"
          fi

          echo "=== Installing dependencies ==="
          npm ci

          echo "=== Building application ==="
          npm run build
          echo "Build complete. Checking dist/server/index.js..."
          ls -lh dist/server/index.js

          echo "=== Running database migrations ==="
          npm run db:push || echo "Warning: Database migration failed or no changes"

          echo "=== Checking PM2 status ==="
          if /usr/bin/pm2 describe facnet-validator >/dev/null 2>&1; then
            echo "PM2 processes exist - performing zero-downtime reload..."
            /usr/bin/pm2 reload ecosystem.config.cjs --update-env
            echo "PM2 reload completed with exit code: $?"
          else
            echo "No existing PM2 processes - performing initial start..."
            /usr/bin/pm2 start ecosystem.config.cjs
            echo "PM2 start completed with exit code: $?"
          fi

          echo "=== Saving PM2 configuration ==="
          /usr/bin/pm2 save

          echo "=== Waiting for processes to stabilize ==="
          sleep 5

          echo "=== Verifying deployment ==="
          /usr/bin/pm2 status facnet-validator

          echo "=== Health check ==="
          curl -f http://localhost:5000/api/health && echo "" || echo "Warning: Health check failed"

          echo "=== Deployment completed successfully! ==="
          '

    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ubuntu
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Check if application is responding
          sleep 10
          curl -f -k https://148.113.196.245 > /dev/null && echo "✅ Application is responding" || echo "❌ Application is not responding"

          # Check PM2 status as facnet user
          sudo -u facnet pm2 status facnet-validator